#!/bin/bash
#
# This script will be the shell for bkp UNIX user on the host being backed up. It
# reads from stdin a single argument, which is the destination to which to upload the
# esults of the backup.
#
# Note: when ssh invokes the shell via 'ssh bkp@host cmd', the shell is passed '-c cmd'
#
# cya_shell expects these to be defined in /etc/cya/backup, for example:
#
#	SOURCE_DIR="/"
# 	ARCHIVE_HOST="scp://archive@moya.dev.lsstcorp.org"
# 	BACKUP_CMD=/opt/cya/duplicity-ex-snap
# 	BACKUP_OPTS="--no-encryption --asynchronous-upload --volsize 100 --exclude /data --exclude /home --exclude /root --exclude /var"
#

set -e

#. /etc/cya/backup

#[[ -z $ARCHIVE_HOST ]] && { echo 'cya_shell configuration error: $ARCHIVE_HOST undefined. Define it in /etc/cya/backup.'; exit -1; }
#[[ -z $SOURCE_DIR ]]   && { echo 'cya_shell configuration error: $SOURCE_DIR undefined. Define it in /etc/cya/backup.';   exit -1; }
#[[ -z $BACKUP_CMD ]]   && { echo 'cya_shell configuration error: $BACKUP_CMD undefined. Define it in /etc/cya/backup.';   exit -1; }
#[[ -z $BACKUP_OPTS ]]  && { echo 'cya_shell configuration error: $BACKUP_OPTS undefined. Define it in /etc/cya/backup.';  exit -1; }

[[ $# -ne 2 ]]   && { echo "Invocation error."; exit -1; }
[[ $1 == '-c' ]] || { echo "Invocation error."; exit -1; }

# perform backup
#echo $BACKUP_CMD $SOURCE_DIR "$ARCHIVE_HOST/$2" $BACKUP_OPTS
#exec $BACKUP_CMD $SOURCE_DIR "$ARCHIVE_HOST/$2" $BACKUP_OPTS
sudo /etc/cya/backup "$2"
#ssh -A archive@moya.dev.lsstcorp.org ls
