#!/bin/bash
#
# Simple script to restore all hard links, ACLs and xattrs
# Must be run from the base of the restored file system
#

set -e

cat .dupext/hardlinks.txtz |
perl -e '
	$/ = "\0";
	while(<>)
	{
		chomp;
		($i, $l, $fn) = /^(\d+) (\d+) (.*)/s;
		if($i == $i0)
		{
			link $fn0, $fn or die("Failed to link $fn0 to $fn\n");
		}
		else
		{
			$i0 = $i; $fn0 = $fn;
		}
	}
'

setfacl --restore=.dupext/acl.txt
setfattr -h --restore=.dupext/xattr.txt

